development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: love4movies
  username: root
  password: ""

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/production.sqlite3
  pool: 5
  timeout: 5000

cucumber:
  <<: *test
